# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: codemagic cicd test
        scripts:
            - name: unit testing
              script: ./gradlew test
            - name: Launch emulator
              script: |
                  cd $ANDROID_HOME/tools
                  emulator -avd emulator &
                  adb wait-for-device
            - name: UI Test with Espresso
              script: |
                  set -e
                  ./gradlew connectedAndroidTest
                  adb logcat -d > emulator.log
              test_report: app/build/outputs/androidTest-results/connected/*.xml
            - ./gradlew build
        artifacts:
            - app/build/outputs/**/*.apk