# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: codemagic cicd test
        environment:
            vars:
                SONAR_TOKEN: Encrypted(Z0FBQUFBQmY1SllEeEE4RFNlQmFwWEFGVEEwMHBPNmJjZi1tc19femNJQUZYZ3BYVXp3XzI2UlFGLWJIWGJ6SXZKV2R0bktTbHV5R25PLVcwRTFjOTBHS2Z1TFJrVXJTT041dzlPNFF2VkdxLTdNODRod251UFJOMzVSWngzb1FDeFZYSHpDcWdVNzk=)
                SONAR_PROJECT_KEY: Encrypted(Z0FBQUFBQmY1Sll6aTlqR2pVRzRhYWF3YjZ3ak5QamZ5eW5DdVpROUZLcl9MZW5BZEtrRE8tck14Qm9ncWstckpwYXhGWFZibDVyS0xPNVAwa19MdEtUUmhBWXlOZGI4TXlZOTljX0FrWFJGZ190djBvNDFtRG5kYmRCUVcyWFJrV3h3Wm9GWUFjVUk=)
                SONAR_ORG_KEY: Encrypted(Z0FBQUFBQmY1SlpOMHZtWFJoNkQyNHdJTzZNMm16VG5HV1pORTNzNHlGdmd3R3pBcjkzSVNEQ0gyQ015YXZxM1ZuNHRJLXhac3RaZ3pKYklPaXA4aXc1S3BaT1ByQmk2VTIwNzA3WDNWT2xxN1l2TkFNNlZyWVdqaHVBQ3ZIaFM4QlZ6Zkt2emVLOWc=)
        scripts:
            - name: unit testing
              script: ./gradlew test
            - name: Launch emulator
              script: |
                  cd $ANDROID_HOME/tools
                  emulator -avd emulator &
                  adb wait-for-device
            - name: UI Test with Espresso
              script: |
                  set -e
                  ./gradlew connectedAndroidTest
                  adb logcat -d > emulator.log
              test_report: app/*.xml
            - ./gradlew build

            - name: quality with sonar cloud
              script: |                
                ./gradlew sonarqube \
                -Dsonar.projectKey=$SONAR_PROJECT_KEY \
                -Dsonar.organization=$SONAR_ORG_KEY \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.login=$SONAR_TOKEN \
                -Dsonar.projectVersion=1.0.0-cm  
                -Dsonar.coverage.jacoco.xmlReportPaths=app/*.xml

        artifacts:
            - app/build/outputs/**/*.apk

        publishing:
          slack:
            channel: '#codemagic-pipeline'
            notify_on_build_start: true    # To receive a notification when a build starts
            notify:
              success: true               # To not receive a notification when a build succeeds
              failure: true               # To not receive a notification when a build fails
