# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: codemagic cicd test
        scripts:
            - name: unit testing
              script: ./gradlew test
            - ./gradlew build
        artifacts:
            - app/build/outputs/**/*.apk