# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: codemagic cicd test
        scripts:
            - ./gradlew assembleRelease
        artifacts:
            - app/build/outputs/**/*.apk