# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: codemagic cicd test
        environment:
            vars:
                SONAR_TOKEN: Encrypted(Z0FBQUFBQmYxS2ljM1d3N3dyQXNRMXF5OUlYUzJXbzBtcUdfSmowUmhpSGVvSGgxT1FvOGxRdnliM1NSdW9kLUZZWjFNOENqNjBVdmVrVmFBUklSb3lmNWpBSHd5ZlRlVGRtSFAxakY3TzNFY2g1eElRczg4cHZScXNaNVc5T19MaDFxbXFheTBiOHQ=)
                SONAR_PROJECT_KEY: Encrypted(Z0FBQUFBQmYxS24tRVBXVF9pUzhqc1pWbDVvVlU3OUtoekxRMWNuZnJ0M2tiV1JfdkVLX2NVZUIzQUV5SmlvWnB3VFlBUW5wemFjVHFLWG9sS0hyQXc0akZSMFVYbkUyQXotZXI0SUFoTW8tZFh6a0ZUcUJodkU9)
                SONAR_ORG_KEY: Encrypted(Z0FBQUFBQmYxS282a2FKWjEyX1J5a0xrc1FDckdFSTJmbnFtOUhHNWJQSkZkMHd6djVocU9MQjhCVGwzdWVCZWF6UUZvRTJKQkxvbWVuQzJjbDRxbjVUaVFjVWFrTTZJYWxSYkZHRjJWb2pfRlc4NVRhMjNZcUE9)
        scripts:

            - name: quality with sonar cloud
              script: |
                  # Generate and upload code analysis report
                  ./gradlew sonarqube \
                  -Dsonar.projectKey=$SONAR_PROJECT_KEY \
                  -Dsonar.organization=$SONAR_ORG_KEY \
                  -Dsonar.host.url=https://sonarcloud.io \
                  -Dsonar.login=$SONAR_TOKEN \
                  -Dsonar.projectVersion=1.0.0-cm
        artifacts:
            - app/build/outputs/**/*.apk