# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: codemagic cicd test
        environment:
            vars:
                SONAR_TOKEN: Encrypted(Z0FBQUFBQmY1Sm1IRWo3cHZrWV82dXZzblpFMEkxTHF6Tm9ZWlFJVmkxalRQYk1aQ2tCY05FVENha2Z4ZURINnlPNVYzQnl2NGIxTWFXbVp2eU11Q05BclRXUFJfcm0xeHdjbXQzRlRHVG5VcXFlOG9GdEh1RHF1WTdWa2o3VElja09WUUtMd0ljZlk=)
                SONAR_PROJECT_KEY: Encrypted(Z0FBQUFBQmY1SmxPUkdGamU5MjkwMkFSclp4NHJ5VWhKQUh2N2dsT0tXOEsyclNpbENvNTgtYUdSMVMxc3Q2bXFjWDlaM2dFUldIUFNDcUx6ODQ0WmNzektSSGxEZlUwbHpWdnAta0lJdzZFTkotRlhyZzJuQVk9)
                SONAR_ORG_KEY: Encrypted(Z0FBQUFBQmY1SmxwbXlmRk1Yc3FMZXN4WHNLLUFnTU9FQTZWTlFYUFhXR2pzWGxMWDF4cmd6MTZPTTltWnZiWU4wdDFQNlZJcFo1TlhBY0I5VFpXaTJLSkRBVW9BMnl4TE8zd0xXZGhBR0llMEFqVTl1b0JobDgyOHBIX2hVUE50WVgwTzk4Y1BWbV8=)
        
        scripts:
                       
            - name : App Assembling
              script: ./gradlew assembleDebug 
            
            - name: Preparing Sonar Analysis
              script: |
                brew tap AdoptOpenJDK/openjdk \
                brew install --cask adoptopenjdk11 \
                export JAVA_HOME=`/usr/libexec/java_home -v 11`
            
                 
