# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: codemagic cicd test
        #environment:
            #vars:
               # SONAR_TOKEN: Encrypted(Z0FBQUFBQmY0ZW9fZ3JQZ3ZRa1FOYy1GbjBmRklfT2RUT25oRnJjeHZVR1M0NkZJV09vTGVHdzdSQV9qRFd5X25vaTJSX0VXeTdzdkk2WWlHdnFwc1hiSzFPdGdpNnZoUjcwYXpuVDlHbnpoSzRCTm94bTAwcENILVV3S2lvb1U3TFFSMUZDejh5YTQ=)
               # SONAR_PROJECT_KEY: Encrypted(Z0FBQUFBQmY0ZXJhU0FIRmJ2NEo5OGdBSlRSM1E4ZUw1YWQtbEtkVVlHS1JvVW1yT2dBLWJuOFVDekpjUG8zSV9lakpFWEtlX2txQUw0RVliYWpYb1M3cnUtcGFoZHlXMXhMdkcxOWE0WVdDUkp0NTRaMWdLY3c9)
             #   SONAR_ADDRESS: Encrypted(Z0FBQUFBQmY0ZW11OU9wRzJKWEh6a0t4TFJqdUp1OXZYVVVXSXRSdjNxLXRMOVN3ZXNyYWJTUWFwTHhpVEFWdzhEaFIxcG1NRFpsRlZ0MTZGaHlCeFRmMkZUZ1JuQ2llU2c9PQ==)
        scripts:
            - name: unit testing
              script: ./gradlew test
            - name: Launch emulator
              script: |
                  cd $ANDROID_HOME/tools
                  emulator -avd emulator &
                  adb wait-for-device
            - name: UI Test with Espresso
              script: |
                  set -e
                  ./gradlew connectedAndroidTest
                  adb logcat -d > emulator.log
              test_report: app/*.xml
            - ./gradlew build
            #- name: quality with sonar cloud
              #script: |
              #./gradlew sonarqube \
              # -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              # -Dsonar.host.url=$SONAR_ADDRESS \
              # -Dsonar.login=$SONAR_TOKEN \
          #-Dsonar.projectVersion=1.0.0-cm

        artifacts:
            - app/build/outputs/**/*.apk